sceneName:
  in: path
  name: sceneName
  required: true
  description: "The textual name of the scene."
  schema:
    type: string

trackIndex:
  in: path
  name: trackIndex
  required: true
  description: "The index of the track."
  schema:
    type: integer

clipIndex:
  in: path
  name: clipIndex
  required: true
  description: "The index of the clip on its track."
  schema:
    type: integer